### ISSUE TITLE
Missing documentation for setting up a project from scratch

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#1]
Currently there is little documentation on setting up a project from scratch. The demo project illustrates the structure of a project, however this does not provide information on why and what is actually required in a basic project setup and how to set up your projects in Eclipse.

It would be nice to have some basic instructions in the documentation on this.

Let me know if you need a guinea pig for this. 😃

**Comment by ttveldhuis** [comment]
I've added some initial explanation for setting up a project. Please review :)

**Comment by mpwaldhorst** [comment]
Looks pretty good!
