### ISSUE TITLE
Bundles do not work on Windows and IIS

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#11]
On windows it is necessary to configure IIS to rewrite all requests to index.php in order to be able to retrieve the bundle.

**Comment by ttveldhuis** [comment]
@mpwaldhorst This is solved by pulll request #14 right?

**Comment by mpwaldhorst** [comment]
@ttveldhuis I think we need to evaluate this a little more. right now the web.config file will also be put into the root of the Linux deployment. Maybe it is better not to do this and just put the file in some documentation?

**Comment by mpwaldhorst** [comment]
The file can be downloaded when hosted under apache or nginx. I think this should be only part of documentation so that this file will not be downloadable. Other idea might be to create a separate package/addon for this later. What do you think @ttveldhuis ?

**Comment by mpwaldhorst** [comment]
Added update to documentation https://github.com/Nentix/xentriq.docs/pull/14
