### ISSUE TITLE
Cannot put classes inside addon folder into subfolders

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#13]
It seems like these are not getting autoloaded.

**Comment by ttveldhuis** [comment]
This is possible but the folder names should match the namespace. So if the folder name is `test` the namespace declaration should be 

`namespace test;`

This is so that the autoloader can easily resolve the 'use' path. If desired otherwise please give suggestions :)

**Comment by mpwaldhorst** [comment]
That sounds good, will the name of the addon then be the first part of the namespace or will the namespace begin after?

- private
  - addon.name
    - auth
     - AuthController.php (namespace: auth or addon.name\auth?)

The option to include the addon.name in the namespace might be preferable to keep the namespaces more specific and prevent collision.

**Comment by ttveldhuis** [comment]
Currently it should work without the `addon.name` prefix but we could add that.

**Comment by mpwaldhorst** [comment]
Might be nice, was thinking of a situation where you have multiple addons within your private folder. In this case it might be nice to differentiate the namespaces? What do you think, I'm not sure. Or maybe specify a root namespace for your project, however that seems like configuration which is not needed?

**Comment by ttveldhuis** [comment]
This should work now since the last commit. This only works if the namespace for the class is the same as the folders it is in. So for example;

```
namespace testing/addon/spaces;

class AddonNameSpaceTest {}
```

Should be in a path resolvable from the addon folder as '/testing/addon/spaces'.

**Comment by ttveldhuis** [comment]
Autoloading has been greatly improved recently. I have created an issue in xentriq.docs to document possible namespaces and their folders (https://github.com/Nentix/xentriq.docs/issues/9).
