### ISSUE TITLE
Dependencies on PHP modules should be documented

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#16]
There are a number of dependencies such as php_intl, these should be documented per feature so that the user knows which modules to install if he/she wants to use a feature.

**Comment by mpwaldhorst** [comment]
@ttveldhuis Please add to the following list if you think something is missing:

* php-intl
* php-curl
* php-fileinfo
* php-mbstring ??

**Comment by ttveldhuis** [comment]
I think php-curl is no longer a requirement for xentriq.core.

**Comment by ttveldhuis** [comment]
These should also be added to the composer.json to help users setup a project (in addition to php-intl).

**Comment by mpwaldhorst** [comment]
Will add to documentation and composer file 👍
