### ISSUE TITLE
Missing documentation about templating syntax

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#2]
At the moment there is only the sample project with some indications how the templating syntax works.

It would be nice to get some documentation about things like:

- Including other templates
  - What does the public parameter in [include:'partial/header' public="true"] mean for example
- Calling methods and retrieving data in from addons
  - Forms
- Variables, their naming and how to use them
- If statements, Foreach loops etc.
- Documentation about utilities

Let me know how I can help with this ;)

**Comment by ttveldhuis** [comment]
I've added initial documentation at http://xentriqdocs.readthedocs.io/en/latest/templates.html . Will close this issue when the documentation is up to standard.

**Comment by mpwaldhorst** [comment]
Sounds good, although link seems to be broken

**Comment by ttveldhuis** [comment]
Link is indeed broken after moving documentation around. New link is; http://xentriqdocs.readthedocs.io/en/latest/templates/index.html

**Comment by ttveldhuis** [comment]
Moved to xentriq.docs; https://github.com/Nentix/xentriq.docs/issues/16
