### ISSUE TITLE
Make size of array in foreach available

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#25]
It seems at the moment it is only possible to get the current index in the `foreach`. It can also be very useful to get the size of the current array in the `foreach` body to do check against `index` and the number of items. Alternatively a `boolean` variable such as `isLastItem` could also be provided.

**Comment by ttveldhuis** [comment]
Though we still have to properly test handling of modifiers inside if-statements. It is already possible to access the size of the array using;

`[varArray *sizeof]`

It might be nice to have access to a direct variable containing this information inside the foreach loop though. 

To keep variables as clear as possible I would suggest being able to specify a variable in the foreach tag somehow, which would then contain some meta information like _size_, _index_, _isFirstItem_ and _isLastItem_.

For example;

```
[foreach varArray as var describe meta]
     Value: [var]
     Index: [meta.index]
     Size: [meta.size]
     First: [meta.isFirstItem]
     Last: [meta.isLastItem]
[/foreach]
```

Any ideas on this?

**Comment by mpwaldhorst** [comment]
@ttveldhuis I think this looks good, although I would suggest using the word `with` instead of describe as this reads a little nicer and fits a little better in my opinion, describe sounds like the meta object will be something that will never change. Also, this should be an optional addition, it should still be possible to just declare a foreach as `[foreach varArray as var]`

What do you think?

**Comment by ttveldhuis** [comment]
I've added the functionality to retrieve meta-information for items in a foreach. The `index` variable no longer works.

You can either use;

```
[foreach varArray as var describe meta]
     Value: [var]
     Index: [meta.index]
     Size: [meta.size]
     First: [meta.isFirstItem]
     Last: [meta.isLastItem]
[/foreach]
```

or 

```
[foreach varArray as var provide meta]
     Value: [var]
     Index: [meta.index]
     Size: [meta.size]
     First: [meta.isFirstItem]
     Last: [meta.isLastItem]
[/foreach]
```

I don't really like either of the keywords `describe` or `provide` but if we come up with something better it can be easily added or modified.

**Comment by ttveldhuis** [comment]
8c9152ddc33bcba598b9bc2adc18ae3933bb7855
