### ISSUE TITLE
If-tag limitations

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#26]
Currently the if-tag has the following limitations:
* === & !== not supported DONE
* \>= & <= not supported DONE
* calculations with -,+,*,/,% are not supported

**Comment by mpwaldhorst** [comment]
===, !==, \>= <=are already supported

**Comment by ttveldhuis** [comment]
Since 0.3.5 comparators with more than 3 characters (like === and !==) currently do not work. Needs to be fixed before the next version is released.

**Comment by ttveldhuis** [comment]
2dabb89 adds support for !== and ===

**Comment by ttveldhuis** [comment]
7953e3d adds support for grouping.

**Comment by ttveldhuis** [comment]
I have moved the last item 

> calculations with -,+,*,/,% are not supported

to a separate issue #29 for allowing operators on variables.
