### ISSUE TITLE
Provide helper in Request.php to set locale for current session

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#30]
There should be an easy/straightforward way to set the locale of the current browser session.

Currently one can do:
```
Request::cookie( 'language', 'en' );
```

This is a bit hidden, maybe a wrapper function for this is in order? Also to retrieve the language/locale?

In addition, should this cookie be called locale or language?

**Comment by ttveldhuis** [comment]
Added these two methods;

`Language::setLocale( $locale )`

and 

`Language::getLocale()`
