### ISSUE TITLE
[Bug] In classes in addons which do not provide tag Config::getConfigurationValue does not provide access to the addons configuration

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#32]
It will only load configuration from the project.json file.

**Comment by ttveldhuis** [comment]
You can get configuration values in other classes by providing the name of the addon as second argument to the getConfigurationValue or third argument to getConfigurationValueOrDefault.

So for example, for configuration values for the ManageAddon you would use;

`Config::getConfigurationValue( 'config.value.you.want', 'manage' );`

or 

`Config::getConfigurationValueOrDefault( 'config.value.you.want', 'default', 'manage' );`

**Comment by mpwaldhorst** [comment]
@ttveldhuis This looks like a good solution. I will close this issue but opened another #48 to discuss configuration also related to deployment and different environments.
