### ISSUE TITLE
[Bug] Cannot pass values of variables to included template

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#33]
It is not possible to pass the value of a variable to an included template. The value will always be passed with the value 'false'.

For example:

```[include:'shared/editor-templates/input-text' name="name" value="[object.name]" labelText="{object.name}" /]```

Results in:

```{"name":"name","value":false,"labelText":"Name"}```

**Comment by ttveldhuis** [comment]
This should of course work. Also a good one to add to automated testing.

**Comment by ttveldhuis** [comment]
Should be resolved with e10422e. Still need to improve variable rendering.
