### ISSUE TITLE
Need to escape the square brackets '[' & ']'?

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#36]
in some cases it can be necessary to declare a variable accessor in a input name such as:
```
<input type="text" name="array[0].something" value="value"/>
```
If we then want to replace the index (0) with a variable we would get:
```
<input type="text" name="array[[~input.var default="0"]].something" value="value"/>
```

The variable is in this case however not output/shown as 0. The tag is printed as is and is not handled by the renderer. This is probably related to escaping the square brackets. How is this done?

**Comment by ttveldhuis** [comment]
This is a use-case that is currently not yet taken in to account I think but it can be easily added without the need to escape anything

**Comment by mpwaldhorst** [comment]
Would be great!

**Comment by mpwaldhorst** [comment]
example case:
```[include:'shared/editor-templates/textarea' id="parts[[~include.part.index default="0"]].content"]```

**Comment by ttveldhuis** [comment]
This now works properly.
