### ISSUE TITLE
Multidimensional arrays in form names cause issues/chaining of tags renders incorrectly

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#38]
There seem to be some issues when chainging square brackets with different meaning.

The following renders incorrectly:
```<input type="hidden" name="parts[[~include.part.index default='0']][index *ignore]" />```
OR
```<input type="hidden" name="parts[[~include.part.index default='0']][index]" />```

Both render to:
```<input type="hidden" name="parts[0]" />```

But should be rendered as:
```<input type="hidden" name="parts[0][index]" />```

A variation also renders different than expected:
```<input type="hidden" name="parts[][index *ignore]" />```
OR
```<input type="hidden" name="parts[][index]" />```

Both render to:
```<input type="hidden" name="parts[]" />```

**Comment by ttveldhuis** [comment]
Do you have more contextual information for example the data inside include.part.index and index? I am currently unable to reproduce this issue with the information at hand.

**Comment by mpwaldhorst** [comment]
@ttveldhuis thanks for looking into this.

In this case the include.part.index value holds either nothing or 0. and the index variable is not set as this should be output as `[index]` in the html.

**Comment by ttveldhuis** [comment]
Solved with 36422c6
