### ISSUE TITLE
Files such as the favicon.ico are not returned with the proper content type but always with text/html

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#39]
See the content type being returned for the favicon.ico file when it is placed in the templates directory:
![image](https://user-images.githubusercontent.com/13185130/32698334-2e3774f8-c7a4-11e7-8268-16f7b9119c3a.png)

This does not cause the favicon not to be loaded but should be adressed to ensure the proper MIME types are returned.

**Comment by ttveldhuis** [comment]
Although this has been solved by 7d9be2b - we should open up a discussion on where resources like this should be placed. My initial though was that static images like for example favicon.ico should be placed in the `public` folder. But I can also see a point in having them under for example a resources directory e.g. `content/resources`.

**Comment by mpwaldhorst** [comment]
Opened new issue for the discussion #47
