### ISSUE TITLE
Error after installing Xentriq eclipse plugin

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#4]
The following error is shown in the problems window when installing the Xentriq plugin in Eclipse:

```eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation

org.eclipse.core.contenttype
Error
Sat Apr 22 11:34:04 CEST 2017
Could not create content describer for com.nentix.xentriq.contenttype.xpage. Content type has been disabled.```

**Comment by ttveldhuis** [comment]
Thank you for reporting this. I have seen this error multiple times but it does not seems to cause any problems to the functionality of the Xentriq plugin. Will have to figure out what is causing this error and how to prevent it.

**Comment by ttveldhuis** [comment]
This issue has been resolved in a new release of the Xentriq plugin for Eclipse. (1.20)
