### ISSUE TITLE
Research if `negative` modifier should be allowed on more than just boolean values

### ISSUE THREAD

**Issue by ttveldhuis** [Nentix/xentriq.core#44]
Research if `negative` modifier should be allowed on more than just boolean values

**Comment by mpwaldhorst** [comment]
the only other I could think of where this would be relevant is numerics. This might merit some consideration for completion.

**Comment by ttveldhuis** [comment]
What was meant by this was the exclamation mark modifier. I see no need for adding it for anything else then booleans for now so closing this issue until another arises regarding this.
