### ISSUE TITLE
Request::getCurrentUrl only returnse the current hostname

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#45]
This method should probably return the complete path, however for me it only returns the hostname.

In my $_SERVER variable the REQUEST_URI seems to hold the path after the hostname.

**Comment by ttveldhuis** [comment]
This should be fixed per 9787621 .

**Comment by mpwaldhorst** [comment]
Sorry to say, the getCurrentUrl function still returns only the hostname without the path.

**Comment by mpwaldhorst** [comment]
As mentioned in above comment this was indeed due to version tag.
