### ISSUE TITLE
String conversion error when using variable arguments on variable of type stdclass

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#52]
When for example using json variable argument on a stdclass variable:
Error: Object of class stdClass could not be converted to string
Time:
2017-12-31T22:37:22+01:00
Origin:
/nentix/xentriq.core/src/core/engine/template/TemplateFunctions.php:127

**Comment by ttveldhuis** [comment]
Fixed in 0e91ee4
