### ISSUE TITLE
Errors after form submission are not passed to error destination page

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#54]
The method for redirectAfterAction currently takes an array of errors, however these are not propagated/accessible on the error destination page. To be able to implement form validation through PHP/Xentriq this is a required feature.

**Comment by ttveldhuis** [comment]
Related to #55

**Comment by mpwaldhorst** [comment]
As discussed this will not be possible through `redirectAfterAction`
