### ISSUE TITLE
There should only be one way to pass errors to the form

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#55]
Currently the interface of redirectAfterAction allows to pass an array of errors.
This is not working yet.
However maybe using Utils::registerError should be the only option?
Or should redirectAfterAction be the only option?

**Comment by ttveldhuis** [comment]
registerError should probably be the only options, and moved to a sort of `Response` class.

**Comment by ttveldhuis** [comment]
I'll use this issue for a small polling test;

[![](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Remove%20redirectAfterAction%20and%20only%20use%20Utils%3A%3AregisterError)](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Remove%20redirectAfterAction%20and%20only%20use%20Utils%3A%3AregisterError/vote)
[![](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Remove%20redirectAfterAction%20and%20move%20Response%3A%3AregisterError)](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Remove%20redirectAfterAction%20and%20move%20Response%3A%3AregisterError/vote)
[![](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Support%20both%20redirectAfterAction%20and%20Utils%3A%3AregisterError)](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Support%20both%20redirectAfterAction%20and%20Utils%3A%3AregisterError/vote)
[![](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Support%20both%20redirectAfterAction%20and%20move%20Response%3A%3AregisterError)](https://api.gh-polls.com/poll/01CCG406KY67W80RMP4GGR9ARE/Support%20both%20redirectAfterAction%20and%20move%20Response%3A%3AregisterError/vote)

**Comment by mpwaldhorst** [comment]
@ttveldhuis voted, but that change would mean having a significant version change due to breach of contract with the previous version.

**Comment by mpwaldhorst** [comment]
Some things that in my opinion should be part of the `Response` class:
- way to set Response status code
- way to set response headers
- way to redirect?

**Comment by ttveldhuis** [comment]
Currently the things you describe are currently divided among the Output and Request classes. I think it would be a good approach to merge the functions to a 'Response' class.

I agree that this would be a change that would require a new major version. In that regard I also think the time is approaching for a v1.0.

I have created two new branches;
* development - for small changes and bug fixes that need to be applied to a minor version.
* version_1_0 - for all changes big and small for the first major release.

**Comment by ttveldhuis** [comment]
Implemented and available in version_1_0 branch (unreleased).
