### ISSUE TITLE
Add inline-documentation and generate API reference

### ISSUE THREAD

**Issue by ttveldhuis** [Nentix/xentriq.core#62]
Add inline-documentation and generate API reference

**Comment by mpwaldhorst** [comment]
are you thinking of something like Javadoc style docs?

**Comment by ttveldhuis** [comment]
@mpwaldhorst yes

**Comment by ttveldhuis** [comment]
Since phpdoc was a bit of a let-down, going to look at https://github.com/FriendsOfPHP/Sami/blob/master/README.rst

**Comment by ttveldhuis** [comment]
Ok, I think Sami is the way to go for now. Documentation can be previewed locally by calling; 

`php tools/sami.phar render .sami.php`

All that's left to do for now is actually adding inline API documentation.

**Comment by mpwaldhorst** [comment]
And where to does it then generate the documentation? In a folder inside the current directory?

**Comment by ttveldhuis** [comment]
Currently documentation gets generated to `build/docs`.

**Comment by ttveldhuis** [comment]
Should be soon available on https://api.xentriq.com
