### ISSUE TITLE
Introduce type safety in core code

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#70]
Being dependent on PHP 7.0 we can use more type safety or type hints on functions. This will help during development and makes the code less error prone. We should consider starting to write at least new code in this way.

**Comment by ttveldhuis** [comment]
Definitely agree on this one.

**Comment by ttveldhuis** [comment]
PHP 7.0 compatible type-safety has now been introduced in most places. We need to open an issue whether or not to keep supporting 7.0 or to continue towards 7.1 in the next version of Xentriq.
