### ISSUE TITLE
Variables passed to implement tag not available

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#82]
When using nested implements as follows:
```
[implement:'components/layout']
    [implement:'components/section' icon="fas fa-star" heading="Popular recipes"]
        <p>test</p>
    [/implement]
[/implement]
```
Everything gets rendered as expected, except that the variables declared on the `components/section` are not available in that template. Inside the `components/section` template the include variable is `NULL`

EDIT: **After futher investigation it seems that variables to implement are not available at all.**

**Comment by ttveldhuis** [comment]
Just to clarify the issue, you mean that the `include` context and any variables declared outside the `implement` tag declaration are unavailable? Meaning, when having the following templates;

**a.xpart**
```
[include.greeting], this is from the implementation template.

[part:'default' /]
```

**b.xpage**
```
This is the implementing template.

[varX=addon->getVarX /]

[implementation:'a' greeting="Welcome"]
And an additional greeting using [include.greeting]. 
We received [varX].
[/implementation]
```

Renders to;

```
This is the implementing template.

Welcome, this is from the implementation template.

And an additional greeting using [include.greeting]. 
We received [varX].
```

**Comment by ttveldhuis** [comment]
If the above behavior is the issue, my first question is, did this use to work before the changes on the v1 branch?

**Comment by ttveldhuis** [comment]
You mean var1 is not available in the `components/section` template or is it not available inside the template to render to the default part '<p>test</p>'?

**Comment by ttveldhuis** [comment]
Working on solving this simultaneously with #85
