### ISSUE TITLE
Define custom globally available variables

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#88]
In some cases it would be nice to define custom variables that are always available throughout the templates.

An example of this would be things like:

* isAuthenticated: Indicating that the current user is logged in, if I can make this globally available this would be more efficient as I do not have to execute a method to retrieve the values so often
* userInfo: Holds the user information, retrieving this only once when rendering would be way more efficient

**Comment by mpwaldhorst** [comment]
@ttveldhuis achieved this by setting these variables to the `$GLOBAL`. 
This needs to be documented and maybe we can create an explicit method for this on `Request.php`?

**Comment by ttveldhuis** [comment]
I am currently working on changing the way variables are loaded. This entails $GLOBAL will not be available in the template anymore. Is this a feature required in v1?

**Comment by ttveldhuis** [comment]
Option to use GLOBALS is no longer available. In the latest commit for version 1.0 you can now use:

`TemplateScope::setVariable`

which will then be available in the template.
