### ISSUE TITLE
Destruct of FlashCache breaks Response::addError behavior

### ISSUE THREAD

**Issue by mpwaldhorst** [Nentix/xentriq.core#90]
In commit [85fd42a60a5d9b2a8efc6ae30fca6d781f42c922](https://github.com/Nentix/xentriq.core/commit/85fd42a60a5d9b2a8efc6ae30fca6d781f42c922) the destruct method of FlashCache was added/modified to clear the cache. This breaks caching behavior in combination with Response::addError.

This should be reverted.

**Comment by ttveldhuis** [comment]
Option to use GLOBALS is no longer available. In the latest commit for version 1.0 you can now use TemplateScope::setVariable which will then be available in the template.
